// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_Z_cpp
NumericVector update_Z_cpp(NumericVector Nstar, const double theta1, const double theta2, const double b, NumericVector Z, const int ntrialAR);
RcppExport SEXP _gse_update_Z_cpp(SEXP NstarSEXP, SEXP theta1SEXP, SEXP theta2SEXP, SEXP bSEXP, SEXP ZSEXP, SEXP ntrialARSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Nstar(NstarSEXP);
    Rcpp::traits::input_parameter< const double >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< const double >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int >::type ntrialAR(ntrialARSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Z_cpp(Nstar, theta1, theta2, b, Z, ntrialAR));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_loop_cpp
NumericVector mcmc_loop_cpp(double burn_d, double nsim_d, double thin_d, double verbose_d, NumericVector Nstar, double T_d, NumericVector b_space, double eta1, double eta2, double phi1, double phi2, double theta1_init, double theta2_init, double b_init, NumericVector Z_init, Function update_Z_fn, Function update_pars_fn);
RcppExport SEXP _gse_mcmc_loop_cpp(SEXP burn_dSEXP, SEXP nsim_dSEXP, SEXP thin_dSEXP, SEXP verbose_dSEXP, SEXP NstarSEXP, SEXP T_dSEXP, SEXP b_spaceSEXP, SEXP eta1SEXP, SEXP eta2SEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP theta1_initSEXP, SEXP theta2_initSEXP, SEXP b_initSEXP, SEXP Z_initSEXP, SEXP update_Z_fnSEXP, SEXP update_pars_fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type burn_d(burn_dSEXP);
    Rcpp::traits::input_parameter< double >::type nsim_d(nsim_dSEXP);
    Rcpp::traits::input_parameter< double >::type thin_d(thin_dSEXP);
    Rcpp::traits::input_parameter< double >::type verbose_d(verbose_dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nstar(NstarSEXP);
    Rcpp::traits::input_parameter< double >::type T_d(T_dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_space(b_spaceSEXP);
    Rcpp::traits::input_parameter< double >::type eta1(eta1SEXP);
    Rcpp::traits::input_parameter< double >::type eta2(eta2SEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type theta1_init(theta1_initSEXP);
    Rcpp::traits::input_parameter< double >::type theta2_init(theta2_initSEXP);
    Rcpp::traits::input_parameter< double >::type b_init(b_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z_init(Z_initSEXP);
    Rcpp::traits::input_parameter< Function >::type update_Z_fn(update_Z_fnSEXP);
    Rcpp::traits::input_parameter< Function >::type update_pars_fn(update_pars_fnSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_loop_cpp(burn_d, nsim_d, thin_d, verbose_d, Nstar, T_d, b_space, eta1, eta2, phi1, phi2, theta1_init, theta2_init, b_init, Z_init, update_Z_fn, update_pars_fn));
    return rcpp_result_gen;
END_RCPP
}
// update_pars_cpp
NumericVector update_pars_cpp(int T, NumericVector b_space, double eta1, double eta2, double phi1, double phi2, NumericVector Z);
RcppExport SEXP _gse_update_pars_cpp(SEXP TSEXP, SEXP b_spaceSEXP, SEXP eta1SEXP, SEXP eta2SEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_space(b_spaceSEXP);
    Rcpp::traits::input_parameter< double >::type eta1(eta1SEXP);
    Rcpp::traits::input_parameter< double >::type eta2(eta2SEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(update_pars_cpp(T, b_space, eta1, eta2, phi1, phi2, Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gse_update_Z_cpp", (DL_FUNC) &_gse_update_Z_cpp, 6},
    {"_gse_mcmc_loop_cpp", (DL_FUNC) &_gse_mcmc_loop_cpp, 17},
    {"_gse_update_pars_cpp", (DL_FUNC) &_gse_update_pars_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_gse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
