# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_Z_cpp <- function(Nstar, theta1, theta2, b, Z, ntrialAR = 1L) {
    .Call(`_gse_update_Z_cpp`, Nstar, theta1, theta2, b, Z, ntrialAR)
}

mcmc_loop_cpp <- function(burn_d, nsim_d, thin_d, verbose_d, Nstar, T_d, b_space, eta1, eta2, phi1, phi2, theta1_init, theta2_init, b_init, Z_init, update_Z_fn, update_pars_fn) {
    .Call(`_gse_mcmc_loop_cpp`, burn_d, nsim_d, thin_d, verbose_d, Nstar, T_d, b_space, eta1, eta2, phi1, phi2, theta1_init, theta2_init, b_init, Z_init, update_Z_fn, update_pars_fn)
}

update_pars_cpp <- function(T, b_space, eta1, eta2, phi1, phi2, Z) {
    .Call(`_gse_update_pars_cpp`, T, b_space, eta1, eta2, phi1, phi2, Z)
}

