################################################################################
#
# Gompertz Model with Poisson Sampling Error: Markov Chain Monte Carlo
#  Posterior Simulation Using Quasi Elliptical Slice Sampler
#
################################################################################


############### description
# This function samples from the posterior distribution of the following model:
#
#           Nstar_t | N_t ~ Poisson(N_t)
#           N_t = exp(Z_t)
#           Z_t = a + (1 + b) Z_{t - 1} + eps_t
#           eps_t ~iid Gauss(0, sigmaSq)
#
# It is used an alternative parametrization, that is:
#
#     theta1 = - a / b
#     theta2 = - sigmaSq / (b * (2 + b))
#     beta = 1 / (1 + exp(b))
#
# which implies
#
#     Z_1, Z_2, ..., Z_T ~ Gauss_T ( theta1 1_T, theta2 SigmaBar)
#     SigmaBar_ij = (1 + b ) ^ abs(i - j)
#
# the priors are
#
#     beta ~ logis(0, c)
#     theta2 ~ invgamma(psi1, psi2)
#     theta1 | theta2 ~ gauss(eta1, eta2 * theta2)
#
# Notice that this implies
#
#     if c == 1 then b ~ U(-1, 0)
#     theta1 ~ student(shape = 2 * psi1, loc = eta1, scale = eta2 * psi2 / psi1)
#
# The following scheme is used
#
#     (1) sample V | beta (posterior of a logistic Kolmogorov)
#
#     (2) sample Z | Nstar, beta, theta2, theta1 using elliptical slice sampling
#
#     (3) beta | Z, V, theta1, theta2 using elliptical slice sampling
#
#     (4) theta2, theta1 | beta, Z
#         (4.1) theta2 | beta, Z ~ invgamma(...)
#         (4.2) theta1 | theta2, beta, Z ~ gauss(...)

#source("extraFunctions.R")
#source("GompPois_likelihood.R")
#source("rpostlogiskolmo.R")

############### function
GompPois_quasiEllipSlice = function(
  nsim, Nstar, psi1, psi2, eta1, eta2, c,
  starter = NULL, burn = 1, thin = 1, verbose = +Inf
) {

  # nsim is the number of simulations to be stored;
  # Nstar is the vector of the data, say Nstar_t, t = 1,2,...,T;
  # psi1, psi2, eta1, eta2, c are the prior parameters, see introduction;
  # starter is a list providing the starter point;
  # burn is the the number of scans to be discarded as burn-in;
  # thin is the thinning parameter;
  # verbose is the period for printing status of the chain.

  # starter must be a list with the following structure:
  #  starter$theta1, starter$theta2, starter$b , starter$Z; or NULL. In the
  #  latter case the starting point is generated by method of moments.

  #--------------
  sub_Gomp_loglike_b = function(b, Z, theta1, theta2) {
    res = 0
    for (t in 2:T) {
      res = res + dnorm(
        Z[t], mean = -b * theta1 + (1 + b) * Z[t - 1],
        sd = sqrt(-b * (2 + b) * theta2), log = TRUE
      )
    }
    return(res)
  }
  #--------------


  ###############--------------- function script

  ### print start time if required
  if(!is.infinite(verbose)) {
    print(paste(
      "GompPois_quasiEllipSlice: start time at ", Sys.time(), sep = ""
    ))
  }

  ### check verbose
  if (verbose == 0) verbose = nsim + 1

  ### check burn
  if (burn <= 0) burn = 1




  ########## initialization

  ##### get starting values

  ### if starting values are not provided then use method of moments
  if (is.null(starter)) {
    starter = GompPois_MoM(Nstar)
    # check if estimated values belong to the support of the parameters
    if(starter$theta2 < 0.01) starter$theta2 = 0.01
    if(starter$b > -0.01) starter$b = -0.01
    if(starter$b < -0.99) starter$b = -0.99
    # sample Z from importance density
    starter$IS = c(GompPois_likelihood(
      Nstar, theta1 = starter$theta1, theta2 = starter$theta2, b = starter$b,
      nsim = 1e+4, log = TRUE, details = TRUE
    ))
    starter$Z = starter$IS$Z[, sample(
      c(1:1e+4), size = 1, replace = FALSE, prob = starter$IS$normWeights
    )]
  }

  ### initialize parameter values
  theta1 = starter$theta1
  theta2 = starter$theta2
  b = starter$b
  Z = starter$Z

  a = -b * theta1
  sigmaSq = -b * (2 + b) * theta2
  beta = log(-b / (1 + b))
  V = pi^2 / 3 # just for initialization, it is not used



  ### sample size
  T = length(Nstar)

  ### initialize inverse of B
  invB = matrix(0, nrow = T, ncol = T)

  ### initialize initial proposal for elliptical slice sampling of Z
  Z_tilde = double(T)

  ### storing vectors
  keep_theta1 = double(nsim)
  keep_theta2 = double(nsim)
  keep_b = double(nsim)




  ########## draw the chain
  for (insim in (1-burn):nsim) {

    ithin = 0

    ##### iterate up to thinning value
    while (ithin < thin) {

      ##########################################################################
      #                                                                        #
      #                                update V                                #
      #                                                                        #
      ##########################################################################

      V = c(rpostlogiskolmo(1, x = beta / sqrt(c)))



      ##########################################################################
      #                                                                        #
      #                                update Z                                #
      #                                                                        #
      ##########################################################################

      strike = sum(Nstar * Z - exp(Z)) - rexp(1)
      delta = runif(1, min = 0, max = 2 * pi)
      delta_min = delta - 2 * pi
      delta_max = delta
      Z_tilde[1] = theta1 + sqrt(theta2) * rnorm(1)
      for (t in 2:T) {
        Z_tilde[t] = a + (1 + b) * Z_tilde[t - 1] + sqrt(sigmaSq) * rnorm(1)
      }

      while (TRUE) {
        Z_prop = Z * cos(delta) + Z_tilde * sin(delta)
        if (sum(Nstar * Z_prop - exp(Z_prop)) >= strike) {
          Z = Z_prop
          break
        } else {
          if (delta < 0) delta_min = delta else delta_max = delta
          delta = runif(1, min = delta_min, max = delta_max)
        }
      }



      ##########################################################################
      #                                                                        #
      #                                update b                                #
      #                                                                        #
      ##########################################################################

      strike = sub_Gomp_loglike_b(b, Z = Z, theta1 = theta1, theta2 = theta2) -
        rexp(1)
      delta = runif(1, min = 0, max = 2 * pi)
      delta_min = delta - 2 * pi
      delta_max = delta
      betaTilde = sqrt(c * V) * rnorm(1)

      while (TRUE) {
        betaProp = beta * cos(delta) + betaTilde * sin(delta)
        bProp = -1 / (1 + exp(-betaProp))
        loglike_bProp = sub_Gomp_loglike_b(
          bProp, Z = Z, theta1 = theta1, theta2 = theta2
        )
        if (loglike_bProp >= strike) {
          beta = betaProp
          b = bProp
          break
        } else {
          if (delta < 0) delta_min = delta else delta_max = delta
          delta = runif(1, min = delta_min, max = delta_max)
        }
      }



      ##########################################################################
      #                                                                        #
      #                        update theta1 and theta2                        #
      #                                                                        #
      ##########################################################################

      invB[1, 1] = 1
      invB[1, 2] = -(1 + b)
      invB[2, 1] = -(1 + b)
      invB[T, T] = 1
      for (t in 2:(T-1)) {
        invB[t, t] = 1 + (1 + b)^2
        invB[t, t + 1] = -(1 + b)
        invB[t + 1, t] = -(1 + b)
      }
      invB = invB / (1 - (1 + b)^2)

      commonFactor = 1 + eta2 * sum(invB)
      rowSums_invB = c(rowSums(invB)) # it is B^-1 %*% 1_T
      #matrixQuadForm_theta2 = invB - eta2 * tcrossprod(rowSums_invB) /
      #  commonFactor

      theta2 = 1 / rgamma(
        1, shape = psi1 + 0.5 * T, rate = psi2 + 0.5 * quad_form(
          invB - eta2 * tcrossprod(rowSums_invB) / commonFactor, Z - eta1
        )
      )

      theta1 = rnorm(
        1, mean = (eta2 * crossprod(rowSums_invB, Z) + eta1) / commonFactor,
        sd = sqrt(theta2 * eta2 / commonFactor)
      )

      a = -b * theta1
      sigmaSq = -b * (2 + b) * theta2



      ##### end of single complete scan
      if (insim > 0) ithin = ithin + 1 else ithin = thin

    }

    ### check if outside of burn-in period
    if (insim > 0) {

      ### keep values
      keep_b[insim] = b
      keep_theta1[insim] = theta1
      keep_theta2[insim] = theta2

      ### print status of the chain
      if (insim %% verbose == 0) {
        print(paste(
          "iteration ", insim, " of ", nsim, " completed at time ", Sys.time(),
          sep = ""
        ))
      }

    }

  }

  ### print end time if required
  if (!is.infinite(verbose)) {
    print(paste("GompPois_quasiEllipSlice: end time at ", Sys.time(), sep = ""))
  }

  ### return results
  return(list(
    theta1 = keep_theta1,
    theta2 = keep_theta2,
    b = keep_b
  ))

}